//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfCommerce
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="id", Namespace="http://schemas.datacontract.org/2004/07/WcfCommerce")]
    public partial class id : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private string firstnameField;
        
        private string lastnameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname
        {
            get
            {
                return this.firstnameField;
            }
            set
            {
                this.firstnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname
        {
            get
            {
                return this.lastnameField;
            }
            set
            {
                this.lastnameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ICustomer")]
public interface ICustomer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetOrderOfCustomer", ReplyAction="http://tempuri.org/ICustomer/GetOrderOfCustomerResponse")]
    WcfCommerce.id GetOrderOfCustomer(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomer/GetOrderOfCustomer", ReplyAction="http://tempuri.org/ICustomer/GetOrderOfCustomerResponse")]
    System.Threading.Tasks.Task<WcfCommerce.id> GetOrderOfCustomerAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ICustomerChannel : ICustomer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomerClient : System.ServiceModel.ClientBase<ICustomer>, ICustomer
{
    
    public CustomerClient()
    {
    }
    
    public CustomerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public CustomerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CustomerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public CustomerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfCommerce.id GetOrderOfCustomer(int id)
    {
        return base.Channel.GetOrderOfCustomer(id);
    }
    
    public System.Threading.Tasks.Task<WcfCommerce.id> GetOrderOfCustomerAsync(int id)
    {
        return base.Channel.GetOrderOfCustomerAsync(id);
    }
}
